apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: infrastructure
  namespace: webgrip
  description: Infrastructure
spec:
  type: department
  profile:
    displayName: Infrastructure
    email: ryan@webgrip.nl
  parent: webgrip-corp
  children: [group:webgrip/backstage]
