apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: webgrip-domains
  namespace: webgrip
  description: A collection of all the domains within the WebGrip organisation
spec:
  targets:
    - ./domains/operations-domain.yaml
    - ./domains/telemetry-domain.yaml
